### ISSUE TITLE
Can't load interstitial ads on Android 7.0

### ISSUE THREAD

**Issue by luckydaemon** [appodeal/Appodeal-Flutter-Plugin#14]
I have encountered an error, where interstitial ads cannot be loaded on devices with Android 7.0 (real device and emulators). Stack trace shows next error:
```
D/Appodeal( 3839): Interstitial [Load Failed]: Yandex - INTERNAL ERROR (4) - eCPM: 0.00, precache: false, expTime: 0, id: UDMyS...
W/System.err( 3839): java.net.UnknownHostException: Unable to resolve host "api.appodealx.com": No address associated with hostname
W/System.err( 3839): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
W/System.err( 3839): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
W/System.err( 3839): 	at java.net.InetAddress.getAllByName(InetAddress.java:752)
W/System.err( 3839): 	at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
W/System.err( 3839): 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
W/System.err( 3839): 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
W/System.err( 3839): 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
W/System.err( 3839): 	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:345)
W/System.err( 3839): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
W/System.err( 3839): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
W/System.err( 3839): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
W/System.err( 3839): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
W/System.err( 3839): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
W/System.err( 3839): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
W/System.err( 3839): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
W/System.err( 3839): 	at io.bidmachine.core.NetworkRequest.process(NetworkRequest.java:155)
W/System.err( 3839): 	at io.bidmachine.core.NetworkRequest.access$100(NetworkRequest.java:30)
W/System.err( 3839): 	at io.bidmachine.core.NetworkRequest$NetworkRequestRunner.run(NetworkRequest.java:513)
W/System.err( 3839): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err( 3839): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err( 3839): 	at java.lang.Thread.run(Thread.java:761)
W/System.err( 3839): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/System.err( 3839): 	at libcore.io.Posix.android_getaddrinfo(Native Method)
W/System.err( 3839): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
W/System.err( 3839): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
W/System.err( 3839): 	... 20 more
D/BidMachineLog( 3839): obtainError: java.net.UnknownHostException: Unable to resolve host "api.appodealx.com": No address associated with hostname(com.android.okhttp.internal.huc.HttpURLConnectionImpl:https://api.appodealx.com/auction/init)
```
This error shows only when trying to load actual ads. Integration screen (Appodeal.setTesting(true)) appears normally without any error.
stack_appodeal_flutter: v1.2.0
appodeal android sdk: v2.11.1.0

**Comment by da2gl** [comment]
Hi @luckydaemon.
You can contact our support team through [the main dashboard](http://appodeal.com/).
They will help with solving your issue with ad networks.
Have a nice day.
