### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Rehckover** [appodeal/Appodeal-Flutter-Plugin#15]
I had a crash when VastActivity try to launch, maybe some problem with obsurfucation and proguard. Any ideas how to fix that?

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eecorp.wordsearch/com.explorestack.iab.vast.activity.VastActivity}: java.lang.RuntimeException: java.lang.NoSuchMethodException: z2.f.values []
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4022)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

Caused by java.lang.RuntimeException: java.lang.NoSuchMethodException: z2.f.values []
       at java.lang.Enum.enumValues(Enum.java:270)
       at java.lang.Enum.access$000(Enum.java:61)
       at java.lang.Enum$1.create(Enum.java:277)
       at java.lang.Enum$1.create(Enum.java:275)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
       at java.lang.Enum.getSharedConstants(Enum.java:289)
       at java.lang.Enum.valueOf(Enum.java:243)
       at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1841)
       at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
       at android.os.Parcel.readSerializable(Parcel.java:3519)
       at android.os.Parcel.readSerializable(Parcel.java:3489)
       at com.explorestack.iab.vast.VastRequest.<init>(:67)
       at com.explorestack.iab.vast.VastRequest$c.createFromParcel(:2)
       at android.os.Parcel.readParcelable(Parcel.java:3345)
       at android.os.Parcel.readValue(Parcel.java:3238)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3635)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.Bundle.getParcelable(Bundle.java:1002)
       at android.content.Intent.getParcelableExtra(Intent.java:9180)
       at com.explorestack.iab.vast.activity.VastActivity.onCreate(:27)
       at android.app.Activity.performCreate(Activity.java:8282)
       at android.app.Activity.performCreate(Activity.java:8262)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

**Comment by da2gl** [comment]
Hi @Rehckover .
You can contact our support team through [the main dashboard](http://appodeal.com/).
They will help with solving your issue with ad networks and crashes.
Have a nice day.
