### ISSUE TITLE
Appodeal crash

### ISSUE THREAD

**Issue by JenshenSoft** [appodeal/Appodeal-Flutter-Plugin#21]
Hello,

I've faced a crash.
It happens during flutter engine init.

The `activity` ref can't be found.

Flutter version: 3.0.2
Appodeal version: 1.2.2

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Required value was null., null, java.lang.IllegalStateException: Required value was null.
	at com.appodeal.appodeal_flutter.d.c(AppodealBaseFlutterPlugin.kt:1)
	at com.appodeal.appodeal_flutter.e.g(AppodealFlutterPlugin.kt:106)
	at yr.i$a.a(MethodChannel.java:4)
	at nr.c.g(DartMessenger.java:1)
	at nr.b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:607)
       at MethodChannel._invokeMethod(platform_channel.dart:167)
```

It could be related that I've integrated flutter as a module in the existing app. 

Thanks!

**Comment by da2gl** [comment]
@JenshenSoft Hello!
Thanks for your issue, we started to investigate this behavior.

**Comment by da2gl** [comment]
@JenshenSoft Hello!
We have released a new version of the SDK in which we have changed the logic. 
If you have any questions/issues I will be glad to answer. 
Have a good day.
